### ISSUE TITLE
SyntaxError on python 3.5

### ISSUE THREAD

**Issue by thijstriemstra** [Deepwalker/trafaret#2]
Upgraded to 0.11 and seeing a SyntaxError:

```
File "/home/foo/.virtualenvs/bar/lib/python3.5/site-packages/trafaret_config/__init__.py", line 3, in <module>
    from .simple import read_and_validate, parse_and_validate
  File "/home/foo/.virtualenvs/bar/lib/python3.5/site-packages/trafaret_config/simple.py", line 4, in <module>
    import trafaret as _trafaret
  File "/home/foo/.virtualenvs/bar/lib/python3.5/site-packages/trafaret/__init__.py", line 1, in <module>
    from .base import (
  File "/home/foo/.virtualenvs/bar/lib/python3.5/site-packages/trafaret/base.py", line 20, in <module>
    from .async import (
  File "/home/foo/.virtualenvs/bar/lib/python3.5/site-packages/trafaret/async.py", line 176
    yield (
    ^
SyntaxError: 'yield' inside async function
```

**Comment by Deepwalker** [comment]
fixed in 0.11.1

**Comment by thijstriemstra** [comment]
Thanks, that fixed it. New error with 0.11.1 (that worked with 0.10.4):

```python
import trafaret as T

primitive_ip_regexp = r'^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$'

TRAFARET = T.Dict({
    T.Key('postgres'):
        T.Dict({
            'database': T.String(),
            'user': T.String(),
            'password': T.String(),
            'host': T.String(),
            'port': T.Int(),
            'minsize': T.Int(),
            'maxsize': T.Int(),
        }),
    T.Key('host'): T.String(regex=primitive_ip_regexp),
    T.Key('port'): T.Int(),
    T.Key('cookie_secret'): T.String(),
    T.Key('static_root_url'): T.String()
})
```

```
    T.Key('host'): T.String(regex=primitive_ip_regexp),
TypeError: __init__() got an unexpected keyword argument 'regex'
```

**Comment by Deepwalker** [comment]
This is not error, use t.Regexp or t.RegexpRaw.

**Comment by Deepwalker** [comment]
And `IP`, `IPv4` and `IPv6` :)

**Comment by thijstriemstra** [comment]
I see, it's taken from an aiohttp demo, I'll open a PR there (see: https://github.com/aio-libs/aiohttp/pull/2187), thanks.

**Comment by thijstriemstra** [comment]
@Deepwalker IPv4 works fine, with `IP` I get this error:

```
    T.Key('host'): T.IP(),
TypeError: __call__() missing 1 required positional argument: 'val'
```

**Comment by Deepwalker** [comment]
From code — `IP = IPv4 | IPv6`
So you need not to instatiate `IP`, it is already instance.

**Comment by thijstriemstra** [comment]
Oh, doh, cheers.
