### ISSUE TITLE
Inconsistent internet trafarets after upgrade to 0.11

### ISSUE THREAD

**Issue by playpauseandstop** [Deepwalker/trafaret#8]
**Long story short:** After upgrade to 0.11 there is no `t.Email()` or `t.URL()` call available due to `TypeError`.

----

In 0.10 we're validating URLs & Emails as,

```py
    on_finish_url = t.URL()
```

```py
def email(*, allow_blank: bool=False, nullable: bool=True) >> t.Trafaret:
     trafaret = t.Email(allow_blank=allow_blank)
     if nullable:
        trafaret = trafaret | t.Null()
     return trafaret >> validate_email
```

But after upgrade to 0.11 there is no `t.URL()` or  `t.Email()` call due to,

```
    on_finish_url = t.URL()
E   TypeError: __call__() missing 1 required positional argument: 'val'
```

or,

```
    trafaret = t.Email(allow_blank=allow_blank)
TypeError: __call__() got an unexpected keyword argument 'allow_blank'
```

Yes, I've updated `t.URL()` call to `t.URL` and temporarily stripped ability to supply blank strings to emails, but I'm not sure what lead to those changes and why it's required now to remember which base trafarets are bound, and which are unbound.

Or is this a new-style to use `t.String` / `t.Int` by default, but not `t.String()` / `t.Int()`?

**Comment by Deepwalker** [comment]
Yeah, you are right. But before long story. We have Trafaret classes and instances of this classes.
So `t.String` is a class, `t.String(max_length=255)` is an instance. And what `t.URL` and `t.Email` are? In previous versions they were classes and in last version they are not classes nor they are instances of any particular Trafaret class. They are composed from other trafarets to mimic previous behaviour.
So they are instances and you cant instantiate them. In first version I did something like `Email = lambda: EmailT` to support previous behaviour.

If you need to support empty Email — `emptible_email = t.Atom('') | t.Email` or something like that.

Asides about remembering — you rarely need this actually because trafarets internal calling `ensure_trafaret` intensively, and `ensure_trafaret` instantiate trafarets if need so. It called on `Dict`, `|`, `&` operations.

No, this is not new style, just all internet trafarets are instances composed from more general trafarets. IPv4 and IPv6 will be rewritten some way.

**Comment by Deepwalker** [comment]
Main trafaret vector is composability + immutability. So new release will include IPv4 and IPv6 as Regexp instances + OnError. And `Or` will lose its mutable `<<` and `|` will work like `&`.

**Comment by playpauseandstop** [comment]
@Deepwalker 

Ok. Got it. Thanks for update. Closing this as ``wontfix``
